build:
    cd rust/web && wasm-pack build --release --target web --out-dir ../../web/dist
    rm ./web/dist/.gitignore

webapp:
    serve -dir web

doc:
    cd rust && cargo doc --open

test:
    cd rust && cargo test

clean:
    cd rust && cargo clean
    rm web/dist/*