dev:
    cd centroids && wasm-pack build --dev --target web --out-dir ../web/dist
    rm ./web/dist/.gitignore

release:
    cd centroids && wasm-pack build --release --target web --out-dir ../web/dist
    rm ./web/dist/.gitignore

webapp:
    serve -dir web

doc:
    cd centroids && cargo doc --open

test:
    cd centroids && cargo test