[package]
name = "telemetry"
version = "0.1.0"
edition.workspace = true

[dependencies]
redis = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
shared = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
testcontainers = "0.27"
testcontainers-modules = { version = "0.15", features = ["redis"] }
uuid = { workspace = true }

[lints]
workspace = true
