[overturemaps]
gers_id = "085ba2a9bfffffff01a888f06236016b"

[bounds]
name = "Edinburgh, defined by queensferry and dalkeith"
point1 = { x = -3.409195, y = 55.992622 }
point2 = { x = -3.066667, y = 55.866667 }