[package]
name = "geo-overturemaps"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
geo = "0.30"
tokio = { version="1.46", features = ["test-util"] }
datafusion = "46.0"
tracing = "0.1"
geozero = { version = "0.14", features = ["with-wkb"] }
