[package]
name = "recorder"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
rustls = { workspace = true }
arrow = { workspace = true }
chrono = { workspace = true }
geo = { workspace = true }
geo-types = { workspace = true }
geo-traits = { workspace = true }
clap = { workspace = true }
medallion = { workspace = true }
model = { workspace = true }
redis = { workspace = true }
serde = { workspace = true }
serde_arrow = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
md5 = { workspace = true }
rusqlite = { workspace = true }
shared = { workspace = true }
telemetry = { workspace = true }
transport = { workspace = true }

[dev-dependencies]
uuid = { workspace = true }
tempfile = { workspace = true }
testcontainers = "0.27"
testcontainers-modules = { version = "0.15", features = ["redis"] }

[lints]
workspace = true
