area := "edinburgh"

overturemaps_base := "/Volumes/PRO-G40/OvertureMaps/data/release/2025-06-25.0"
config_base := "../../../config"
rust_log := "info"

green:
    RUST_LOG={{rust_log}} cargo run --release --bin green -- \
        --config {{config_base}}/{{area}}.toml \
        --overturemaps {{overturemaps_base}}