[package]
name = "transport"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = { workspace = true }
clap = { workspace = true }
datafusion = { workspace = true }
geo-types = { workspace = true }
rusqlite = { workspace = true }
sedona = { workspace = true }
sedona-geoparquet = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
wkt = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
wkb = { workspace = true }

[lints]
workspace = true
