//! Integration test for compressed responses: a client offering to decompress is served
//! compressed, and one that does not is not. Driven through the real router via `oneshot`, no
//! network needed.

use axum::body::Body;
use axum::http::{Request, StatusCode, header};
use server::{AppState, build_app};
use tower::ServiceExt;

fn static_dir() -> String {
    concat!(env!("CARGO_MANIFEST_DIR"), "/static").to_string()
}

async fn fetch(path: &str, accept_encoding: Option<&str>) -> (StatusCode, Option<String>, usize) {
    let mut request = Request::builder().uri(path);
    if let Some(encoding) = accept_encoding {
        request = request.header(header::ACCEPT_ENCODING, encoding);
    }
    let response = build_app(AppState { sink: None }, static_dir())
        .oneshot(request.body(Body::empty()).expect("build request"))
        .await
        .expect("router response");

    let status = response.status();
    let encoding = response
        .headers()
        .get(header::CONTENT_ENCODING)
        .map(|value| value.to_str().expect("an ascii encoding").to_string());
    let body = axum::body::to_bytes(response.into_body(), usize::MAX)
        .await
        .expect("read body");

    (status, encoding, body.len())
}

#[tokio::test]
async fn a_client_that_takes_gzip_is_served_gzip() {
    let (status, encoding, _) = fetch("/index.html", Some("gzip")).await;

    assert_eq!(status, StatusCode::OK);
    assert_eq!(encoding.as_deref(), Some("gzip"));
}

#[tokio::test]
async fn a_client_that_asks_for_nothing_is_served_as_it_is() {
    let (status, encoding, _) = fetch("/index.html", None).await;

    assert_eq!(status, StatusCode::OK);
    assert_eq!(encoding, None);
}

/// The largest thing the site serves, and the reason the layer is here. Generated by
/// `just crossings`, so the assertion is about the saving rather than a size, and the test
/// skips where it has not been copied.
#[tokio::test]
async fn the_crossings_are_worth_compressing() {
    let (status, _, plain) = fetch("/crossings.json", None).await;
    if status == StatusCode::NOT_FOUND {
        eprintln!("no crossings.json in static; run `just crossings`");
        return;
    }

    let (status, encoding, compressed) = fetch("/crossings.json", Some("gzip")).await;

    assert_eq!(status, StatusCode::OK);
    assert_eq!(encoding.as_deref(), Some("gzip"));
    assert!(
        compressed < plain / 2,
        "{compressed} bytes compressed is no saving over {plain}",
    );
}
