[project]
name = "esa-python-uv-direct"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fsspec>=2025.7.0",
    "s3fs>=2025.7.0",
    "zarr>=3.1.0",
]
