[project]
name = "notebook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.2.0",
    "jupysql>=0.10.17",
    "jupyterlab>=4.3.5",
    "toml>=0.10.2",
]
