[package]
name = "domain"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12" }
geozero = "0.14"
tracing = "0.1"

geo-types = { workspace = true }
geo = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]
