[build]
base    = "web/zola"
publish = "web/zola/dist"
command = "zola build"

[build.environment]
ZOLA_VERSION = "0.19.2"

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"
